from abc import ABCMeta, abstractmethod
from trading_engine.Event import EventType
from trading_engine.Event import FillEvent
from subprojects.types.Common import *
import subprojects.misc.LowLevelFuncions as llw

logger = llw.script_logger('EXECUTION')


class ExecutionHandler(object):
    """
    The ExecutionHandler abstract class handles the interaction
    between a set of order objects generated by a Portfolio and
    the ultimate set of Fill objects that actually occur in the
    market. 

    The handlers can be used to subclass simulated brokerages
    or live brokerages, with identical interfaces. This allows
    strategies to be backtested in a very similar manner to the
    live trading engine.
    """

    __metaclass__ = ABCMeta

    @abstractmethod
    def execute_order(self, event):
        """
        Takes an Order event and executes it, producing
        a Fill event that gets placed onto the Events queue.

        Parameters:
        event - Contains an Event object with order information.
        """
        raise NotImplementedError("Should implement execute_order()")


class SimulatedExecutionHandler(ExecutionHandler):
    """
    The simulated execution handler simply converts all order
    objects into their equivalent fill objects automatically
    without latency, slippage or fill-ratio issues.

    This allows a straightforward "first go" test of any strategy,
    before implementation with a more sophisticated execution
    handler.
    """
    
    def __init__(self, pending_orders, config_portfolio):
        """
        Initialises the handler, setting the event queues
        up internally.

        Parameters:
        events - The Queue of Event objects.
        """
        self.pending_orders = pending_orders
        self.config_portfolio = config_portfolio

    def execute_order(self, order, current_date, strategies, deactivated_symbols):
        """
        Simply converts Order objects into Fill objects naively,
        i.e. without any latency, slippage or fill ratio problems.

        Parameters:
        event - Contains an Event object with order information.
        """

        if order.type == EventType.ORDER:

            # Check if Limit order is already performed
            if order.order_type == SignalType.TKP or order.order_type == SignalType.STL or \
                    order.order_type == SignalType.LMT:
                for strategy in strategies:
                    if strategy.strategy_id == order.order_id[0:3]:
                        if strategy.bought[order.symbol] == PositionStatus.STAND_BY:
                            logger.info('Limit order ' + order.order_id + ' aborted because is already performed')
                            return

            # TODO: Always MC market ??
            fill_event = FillEvent(
                current_date, order.symbol, order.order_id, Market.MC, order.order_type, order.strength,
                order.quantity, order.action, order.direction, order.price)

            self.pending_orders.put(fill_event)

            for strategy in strategies:
                if strategy.strategy_id == order.order_id[0:3]:
                    strategy.bought[order.symbol] = PositionStatus.STAND_BY

            if order.action == OrderType.EXIT:
                deactivated_symbols.put(order.symbol)
